/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CoreMembersGroupInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CONDITIONS"
      | "MAX_DEPOSIT_AMOUNT_MINIMUM"
      | "beforeBurnPolicy"
      | "beforeMintPolicy"
      | "beforeRedeemPolicy"
      | "feeCollection"
      | "minimalDeposit"
      | "mintHandler"
      | "owner"
      | "redemptionHandler"
      | "registerShortName"
      | "registerShortNameWithNonce"
      | "service"
      | "setAdvancedUsageFlag"
      | "setFeeCollection"
      | "setMembershipCondition"
      | "setMinimalDeposit"
      | "setMintHandler"
      | "setRedemptionHandler"
      | "setService"
      | "setup"
      | "trust"
      | "trustBatch"
      | "updateMetadataDigest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollectionUpdated"
      | "Initialized"
      | "MembershipConditionEnabled"
      | "MinimalDepositUpdated"
      | "MintHandlerUpdated"
      | "OwnerSet"
      | "RedemptionHandlerUpdated"
      | "ServiceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CONDITIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEPOSIT_AMOUNT_MINIMUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beforeBurnPolicy",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeMintPolicy",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeRedeemPolicy",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimalDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintHandler",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redemptionHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerShortName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerShortNameWithNonce",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "service", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAdvancedUsageFlag",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMembershipCondition",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimalDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRedemptionHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setService",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike[],
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "trust",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trustBatch",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadataDigest",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CONDITIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEPOSIT_AMOUNT_MINIMUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeBurnPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeMintPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeRedeemPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimalDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redemptionHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerShortName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerShortNameWithNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "service", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAdvancedUsageFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMembershipCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimalDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRedemptionHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trust", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trustBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadataDigest",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectionUpdatedEvent {
  export type InputTuple = [feeCollection: AddressLike];
  export type OutputTuple = [feeCollection: string];
  export interface OutputObject {
    feeCollection: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembershipConditionEnabledEvent {
  export type InputTuple = [condition: AddressLike, enabled: boolean];
  export type OutputTuple = [condition: string, enabled: boolean];
  export interface OutputObject {
    condition: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinimalDepositUpdatedEvent {
  export type InputTuple = [minimalDeposit: BigNumberish];
  export type OutputTuple = [minimalDeposit: bigint];
  export interface OutputObject {
    minimalDeposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintHandlerUpdatedEvent {
  export type InputTuple = [newMintHandler: AddressLike];
  export type OutputTuple = [newMintHandler: string];
  export interface OutputObject {
    newMintHandler: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerSetEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionHandlerUpdatedEvent {
  export type InputTuple = [newRedemptionHandler: AddressLike];
  export type OutputTuple = [newRedemptionHandler: string];
  export interface OutputObject {
    newRedemptionHandler: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceUpdatedEvent {
  export type InputTuple = [newService: AddressLike];
  export type OutputTuple = [newService: string];
  export interface OutputObject {
    newService: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoreMembersGroup extends BaseContract {
  connect(runner?: ContractRunner | null): CoreMembersGroup;
  waitForDeployment(): Promise<this>;

  interface: CoreMembersGroupInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CONDITIONS: TypedContractMethod<[], [bigint], "view">;

  MAX_DEPOSIT_AMOUNT_MINIMUM: TypedContractMethod<[], [bigint], "view">;

  beforeBurnPolicy: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "nonpayable"
  >;

  beforeMintPolicy: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      _collateral: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  beforeRedeemPolicy: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: BigNumberish,
      _data: BytesLike
    ],
    [
      [bigint[], bigint[], bigint[], bigint[]] & {
        _ids: bigint[];
        _values: bigint[];
        _burnIds: bigint[];
        _burnValues: bigint[];
      }
    ],
    "nonpayable"
  >;

  feeCollection: TypedContractMethod<[], [string], "view">;

  minimalDeposit: TypedContractMethod<[], [bigint], "view">;

  mintHandler: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  redemptionHandler: TypedContractMethod<[], [string], "view">;

  registerShortName: TypedContractMethod<[], [void], "nonpayable">;

  registerShortNameWithNonce: TypedContractMethod<
    [_nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  service: TypedContractMethod<[], [string], "view">;

  setAdvancedUsageFlag: TypedContractMethod<
    [_flag: BytesLike],
    [void],
    "nonpayable"
  >;

  setFeeCollection: TypedContractMethod<
    [_feeCollection: AddressLike],
    [void],
    "nonpayable"
  >;

  setMembershipCondition: TypedContractMethod<
    [_condition: AddressLike, _enabled: boolean],
    [void],
    "nonpayable"
  >;

  setMinimalDeposit: TypedContractMethod<
    [_minimalDeposit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMintHandler: TypedContractMethod<
    [_mintHandler: AddressLike],
    [void],
    "nonpayable"
  >;

  setRedemptionHandler: TypedContractMethod<
    [_redemptionHandler: AddressLike],
    [void],
    "nonpayable"
  >;

  setService: TypedContractMethod<
    [_service: AddressLike],
    [void],
    "nonpayable"
  >;

  setup: TypedContractMethod<
    [
      _owner: AddressLike,
      _service: AddressLike,
      _mintHandler: AddressLike,
      _redemptionHandler: AddressLike,
      _initialConditions: AddressLike[],
      _name: string,
      _symbol: string,
      _metadataDigest: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  trust: TypedContractMethod<
    [_trustReceiver: AddressLike, _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;

  trustBatch: TypedContractMethod<
    [_coreMembers: AddressLike[], _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMetadataDigest: TypedContractMethod<
    [_metadataDigest: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CONDITIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEPOSIT_AMOUNT_MINIMUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beforeBurnPolicy"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeMintPolicy"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      _collateral: BigNumberish[],
      _amounts: BigNumberish[],
      arg4: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeRedeemPolicy"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: BigNumberish,
      _data: BytesLike
    ],
    [
      [bigint[], bigint[], bigint[], bigint[]] & {
        _ids: bigint[];
        _values: bigint[];
        _burnIds: bigint[];
        _burnValues: bigint[];
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeCollection"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minimalDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintHandler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redemptionHandler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerShortName"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerShortNameWithNonce"
  ): TypedContractMethod<[_nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "service"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAdvancedUsageFlag"
  ): TypedContractMethod<[_flag: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollection"
  ): TypedContractMethod<[_feeCollection: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMembershipCondition"
  ): TypedContractMethod<
    [_condition: AddressLike, _enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinimalDeposit"
  ): TypedContractMethod<[_minimalDeposit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMintHandler"
  ): TypedContractMethod<[_mintHandler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRedemptionHandler"
  ): TypedContractMethod<
    [_redemptionHandler: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setService"
  ): TypedContractMethod<[_service: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setup"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _service: AddressLike,
      _mintHandler: AddressLike,
      _redemptionHandler: AddressLike,
      _initialConditions: AddressLike[],
      _name: string,
      _symbol: string,
      _metadataDigest: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trust"
  ): TypedContractMethod<
    [_trustReceiver: AddressLike, _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustBatch"
  ): TypedContractMethod<
    [_coreMembers: AddressLike[], _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMetadataDigest"
  ): TypedContractMethod<[_metadataDigest: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "FeeCollectionUpdated"
  ): TypedContractEvent<
    FeeCollectionUpdatedEvent.InputTuple,
    FeeCollectionUpdatedEvent.OutputTuple,
    FeeCollectionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MembershipConditionEnabled"
  ): TypedContractEvent<
    MembershipConditionEnabledEvent.InputTuple,
    MembershipConditionEnabledEvent.OutputTuple,
    MembershipConditionEnabledEvent.OutputObject
  >;
  getEvent(
    key: "MinimalDepositUpdated"
  ): TypedContractEvent<
    MinimalDepositUpdatedEvent.InputTuple,
    MinimalDepositUpdatedEvent.OutputTuple,
    MinimalDepositUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MintHandlerUpdated"
  ): TypedContractEvent<
    MintHandlerUpdatedEvent.InputTuple,
    MintHandlerUpdatedEvent.OutputTuple,
    MintHandlerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerSet"
  ): TypedContractEvent<
    OwnerSetEvent.InputTuple,
    OwnerSetEvent.OutputTuple,
    OwnerSetEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionHandlerUpdated"
  ): TypedContractEvent<
    RedemptionHandlerUpdatedEvent.InputTuple,
    RedemptionHandlerUpdatedEvent.OutputTuple,
    RedemptionHandlerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceUpdated"
  ): TypedContractEvent<
    ServiceUpdatedEvent.InputTuple,
    ServiceUpdatedEvent.OutputTuple,
    ServiceUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeCollectionUpdated(address)": TypedContractEvent<
      FeeCollectionUpdatedEvent.InputTuple,
      FeeCollectionUpdatedEvent.OutputTuple,
      FeeCollectionUpdatedEvent.OutputObject
    >;
    FeeCollectionUpdated: TypedContractEvent<
      FeeCollectionUpdatedEvent.InputTuple,
      FeeCollectionUpdatedEvent.OutputTuple,
      FeeCollectionUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MembershipConditionEnabled(address,bool)": TypedContractEvent<
      MembershipConditionEnabledEvent.InputTuple,
      MembershipConditionEnabledEvent.OutputTuple,
      MembershipConditionEnabledEvent.OutputObject
    >;
    MembershipConditionEnabled: TypedContractEvent<
      MembershipConditionEnabledEvent.InputTuple,
      MembershipConditionEnabledEvent.OutputTuple,
      MembershipConditionEnabledEvent.OutputObject
    >;

    "MinimalDepositUpdated(uint256)": TypedContractEvent<
      MinimalDepositUpdatedEvent.InputTuple,
      MinimalDepositUpdatedEvent.OutputTuple,
      MinimalDepositUpdatedEvent.OutputObject
    >;
    MinimalDepositUpdated: TypedContractEvent<
      MinimalDepositUpdatedEvent.InputTuple,
      MinimalDepositUpdatedEvent.OutputTuple,
      MinimalDepositUpdatedEvent.OutputObject
    >;

    "MintHandlerUpdated(address)": TypedContractEvent<
      MintHandlerUpdatedEvent.InputTuple,
      MintHandlerUpdatedEvent.OutputTuple,
      MintHandlerUpdatedEvent.OutputObject
    >;
    MintHandlerUpdated: TypedContractEvent<
      MintHandlerUpdatedEvent.InputTuple,
      MintHandlerUpdatedEvent.OutputTuple,
      MintHandlerUpdatedEvent.OutputObject
    >;

    "OwnerSet(address)": TypedContractEvent<
      OwnerSetEvent.InputTuple,
      OwnerSetEvent.OutputTuple,
      OwnerSetEvent.OutputObject
    >;
    OwnerSet: TypedContractEvent<
      OwnerSetEvent.InputTuple,
      OwnerSetEvent.OutputTuple,
      OwnerSetEvent.OutputObject
    >;

    "RedemptionHandlerUpdated(address)": TypedContractEvent<
      RedemptionHandlerUpdatedEvent.InputTuple,
      RedemptionHandlerUpdatedEvent.OutputTuple,
      RedemptionHandlerUpdatedEvent.OutputObject
    >;
    RedemptionHandlerUpdated: TypedContractEvent<
      RedemptionHandlerUpdatedEvent.InputTuple,
      RedemptionHandlerUpdatedEvent.OutputTuple,
      RedemptionHandlerUpdatedEvent.OutputObject
    >;

    "ServiceUpdated(address)": TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;
    ServiceUpdated: TypedContractEvent<
      ServiceUpdatedEvent.InputTuple,
      ServiceUpdatedEvent.OutputTuple,
      ServiceUpdatedEvent.OutputObject
    >;
  };
}
