/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NameRegistry } from "./NameRegistry";
export * as factories from "./factories";
export { NameRegistry__factory } from "./factories/NameRegistry__factory";
