export const V2HubFunctionNames = {
    'advancedUsageFlags': null,
    'avatars': null,
    'balanceOf': null,
    'balanceOfBatch': null,
    'balanceOfOnDay': null,
    'burn': null,
    'calculateIssuance': null,
    'calculateIssuanceWithCheck': null,
    'convertBatchInflationaryToDemurrageValues': null,
    'convertInflationaryToDemurrageValue': null,
    'day': null,
    'groupMint': null,
    'inflationDayZero': null,
    'inviteHuman': null,
    'isApprovedForAll': null,
    'isGroup': null,
    'isHuman': null,
    'isOrganization': null,
    'isPermittedFlow': null,
    'isTrusted': null,
    'migrate': null,
    'mintPolicies': null,
    'operateFlowMatrix': null,
    'personalMint': null,
    'registerCustomGroup': null,
    'registerGroup': null,
    'registerHuman': null,
    'registerOrganization': null,
    'safeBatchTransferFrom': null,
    'safeTransferFrom': null,
    'setAdvancedUsageFlag': null,
    'setApprovalForAll': null,
    'stop': null,
    'stopped': null,
    'supportsInterface': null,
    'toTokenId': null,
    'totalSupply': null,
    'treasuries': null,
    'trust': null,
    'trustMarkers': null,
    'uri': null,
    'wrap': null,
    
}
export type V2HubFunctionName = keyof typeof V2HubFunctionNames;

