/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CirclesCoreAddresses {
  export type CirclesCoreStruct = {
    hub: AddressLike;
    standardTreasury: AddressLike;
    nameRegistry: AddressLike;
    erc20Lift: AddressLike;
  };

  export type CirclesCoreStructOutput = [
    hub: string,
    standardTreasury: string,
    nameRegistry: string,
    erc20Lift: string
  ] & {
    hub: string;
    standardTreasury: string;
    nameRegistry: string;
    erc20Lift: string;
  };
}

export interface CMGroupDeployerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createCMGroup"
      | "getCirclesCore"
      | "lpDeployer"
      | "masterCopyCMGroup"
      | "redemptionOperator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CMGroupCreated" | "MasterCopyDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createCMGroup",
    values: [AddressLike, AddressLike[], string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCirclesCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "masterCopyCMGroup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionOperator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createCMGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCirclesCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpDeployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "masterCopyCMGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionOperator",
    data: BytesLike
  ): Result;
}

export namespace CMGroupCreatedEvent {
  export type InputTuple = [
    proxy: AddressLike,
    owner: AddressLike,
    mintHandler: AddressLike,
    redemptionHandler: AddressLike,
    liquidityProvider: AddressLike
  ];
  export type OutputTuple = [
    proxy: string,
    owner: string,
    mintHandler: string,
    redemptionHandler: string,
    liquidityProvider: string
  ];
  export interface OutputObject {
    proxy: string;
    owner: string;
    mintHandler: string;
    redemptionHandler: string;
    liquidityProvider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MasterCopyDeployedEvent {
  export type InputTuple = [mastercopy: AddressLike];
  export type OutputTuple = [mastercopy: string];
  export interface OutputObject {
    mastercopy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CMGroupDeployer extends BaseContract {
  connect(runner?: ContractRunner | null): CMGroupDeployer;
  waitForDeployment(): Promise<this>;

  interface: CMGroupDeployerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCMGroup: TypedContractMethod<
    [
      _service: AddressLike,
      _initialConditions: AddressLike[],
      _name: string,
      _symbol: string,
      _metadataDigest: BytesLike
    ],
    [
      [string, string, string, string] & {
        proxy: string;
        mintHandler: string;
        redemptionHandler: string;
        liquidityProvider: string;
      }
    ],
    "nonpayable"
  >;

  getCirclesCore: TypedContractMethod<
    [],
    [CirclesCoreAddresses.CirclesCoreStructOutput],
    "view"
  >;

  lpDeployer: TypedContractMethod<[], [string], "view">;

  masterCopyCMGroup: TypedContractMethod<[], [string], "view">;

  redemptionOperator: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCMGroup"
  ): TypedContractMethod<
    [
      _service: AddressLike,
      _initialConditions: AddressLike[],
      _name: string,
      _symbol: string,
      _metadataDigest: BytesLike
    ],
    [
      [string, string, string, string] & {
        proxy: string;
        mintHandler: string;
        redemptionHandler: string;
        liquidityProvider: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCirclesCore"
  ): TypedContractMethod<
    [],
    [CirclesCoreAddresses.CirclesCoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpDeployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "masterCopyCMGroup"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redemptionOperator"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CMGroupCreated"
  ): TypedContractEvent<
    CMGroupCreatedEvent.InputTuple,
    CMGroupCreatedEvent.OutputTuple,
    CMGroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MasterCopyDeployed"
  ): TypedContractEvent<
    MasterCopyDeployedEvent.InputTuple,
    MasterCopyDeployedEvent.OutputTuple,
    MasterCopyDeployedEvent.OutputObject
  >;

  filters: {
    "CMGroupCreated(address,address,address,address,address)": TypedContractEvent<
      CMGroupCreatedEvent.InputTuple,
      CMGroupCreatedEvent.OutputTuple,
      CMGroupCreatedEvent.OutputObject
    >;
    CMGroupCreated: TypedContractEvent<
      CMGroupCreatedEvent.InputTuple,
      CMGroupCreatedEvent.OutputTuple,
      CMGroupCreatedEvent.OutputObject
    >;

    "MasterCopyDeployed(address)": TypedContractEvent<
      MasterCopyDeployedEvent.InputTuple,
      MasterCopyDeployedEvent.OutputTuple,
      MasterCopyDeployedEvent.OutputObject
    >;
    MasterCopyDeployed: TypedContractEvent<
      MasterCopyDeployedEvent.InputTuple,
      MasterCopyDeployedEvent.OutputTuple,
      MasterCopyDeployedEvent.OutputObject
    >;
  };
}
